[package]
name = "lazytodo"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = "0.4.39"
color-eyre = "0.6.3"
crossterm = "0.28.1"
fakeit = "1.3.0"
itertools = "0.13.0"
ratatui = "0.29.0"
serde = {version = "1.0.216", features = ["derive"]}
unicode-width = "0.2.0"
